# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-11 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20180211_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
