# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-11 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_auto_20180211_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='usuario',
        ),
    ]
